/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myfirstproject;

import static org.junit.jupiter.api.Assertions.*;
import static org.assertj.core.api.Assertions.assertThat;
import static java.lang.invoke.MethodHandles.lookup;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.SessionId;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import io.github.bonigarcia.wdm.WebDriverManager;

class HelloWorldChromeJupiterTest {

    Logger log = LoggerFactory.getLogger(lookup().lookupClass());
    WebDriver driver;

    @BeforeAll
    static void setupClass() {
        WebDriverManager.chromedriver().setup();
    }

    @BeforeEach
    void setup() {
        driver = new ChromeDriver();
    }

    @AfterEach
    void teardown() {
        driver.quit();
    }

    @Test
    void testBasicMethods() {
	String sutUrl = "https://bonigarcia.dev/selenium-webdriver-java/";
        driver.get(sutUrl);
        assertThat(driver.getTitle()).contains("Selenium WebDriver");
	assertThat(driver.getCurrentUrl()).isEqualTo(sutUrl);
	assertThat(driver.getPageSource()).containsIgnoringCase("</html>");
    }

    @Test
    void testSessionId(){
	driver.get("https://bonigarcia.dev/selenium-webdriver-java/");

	SessionId sessionId = ((RemoteWebDriver) driver).getSessionId();

	assertThat(sessionId).isNotNull();

	log.debug("The sessionId is {}",sessionId.toString());
    }

}
